-- 1. Create Claims Table (if not exists)
-- Note: User provided schema uses UUID for user references.
CREATE TABLE IF NOT EXISTS claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL REFERENCES items(id),
  claimant_id UUID NOT NULL REFERENCES users(id),
  proof_description TEXT NOT NULL,
  proof_image_url TEXT,
  status TEXT DEFAULT 'pending', -- pending, approved, rejected
  admin_notes TEXT,
  rejection_reason TEXT,
  verified_by_user_id UUID REFERENCES users(id),
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_claims_item_id ON claims(item_id);
CREATE INDEX IF NOT EXISTS idx_claims_claimant_id ON claims(claimant_id);
CREATE INDEX IF NOT EXISTS idx_claims_status ON claims(status);

-- 2. Create Notifications Table (if not exists)
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL,
  item_id BIGINT,
  claim_id BIGINT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);

-- 3. Enable RLS
ALTER TABLE claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 4. Claims Policies

-- Allow users to create their own claims
-- auth.uid() returns uuid, which matches claimant_id type now.
CREATE POLICY "Users can create claims" ON claims
  FOR INSERT
  WITH CHECK (auth.uid() = claimant_id);

-- Allow users to view their own claims
CREATE POLICY "Users can view own claims" ON claims
  FOR SELECT
  USING (auth.uid() = claimant_id);

-- Allow finders (owners of the item) to view claims on their items
-- items.user_id must also be UUID in the DB if users.id is UUID.
-- However, user provided schema only showed claims/notifications.
-- We assume items.user_id is also UUID based on consistency.
CREATE POLICY "Finders can view claims on their items" ON claims
  FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM items
    WHERE items.id = claims.item_id
    AND items.user_id = auth.uid()
  ));

-- Allow finders to update claims on their items (e.g. status)
CREATE POLICY "Finders can update claims on their items" ON claims
  FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM items
    WHERE items.id = claims.item_id
    AND items.user_id = auth.uid()
  ));

-- 5. Notifications Policies

-- Allow users to view their own notifications
CREATE POLICY "Users can view own notifications" ON notifications
  FOR SELECT
  USING (auth.uid() = user_id);

-- Allow users to create notifications for others
CREATE POLICY "Users can create notifications" ON notifications
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');
